# Import Libraries

In [2]:
import sqlite3
import pandas as pd

# Load the CSV

In [31]:
df = pd.read_csv("D:/Computing Stastic 2/python/Decodelab/cleaned_dataset_final.csv")

df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

# Create a SQLite Database

In [6]:
conn = sqlite3.connect("sales.db")

df.to_sql(
    "sales",
    conn,
    if_exists="replace",
    index=False
)

print("Database Created Successfully!")

Database Created Successfully!

# See All Columns

In [8]:
pd.read_sql("""
SELECT *
FROM sales
LIMIT 10;
""", conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
5,ORD200005,2023-10-23,C37249,Phone,2,245.86,934 Main St,Credit Card,Shipped,TRK72976927,4,SAVE10,Instagram,491.72
6,ORD200006,2025-06-17,C83492,Laptop,1,664.42,986 Main St,Gift Card,Returned,TRK96417362,6,SAVE10,Facebook,664.42
7,ORD200007,2023-05-12,C41460,Monitor,5,149.55,706 Main St,Cash,Shipped,TRK78809193,9,FREESHIP,Facebook,747.75
8,ORD200008,2025-04-02,C26817,Phone,2,134.28,904 Main St,Gift Card,Cancelled,TRK61042692,2,no Coupon,Email,268.56
9,ORD200009,2023-11-21,C31946,Desk,4,509.38,102 Main St,Credit Card,Shipped,TRK33478363,6,SAVE10,Google,2037.52

# Display all records

In [9]:
pd.read_sql("""
SELECT *
FROM sales;
""", conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,no Coupon,Facebook,1325.06
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

# Display only Product and TotalPrice

In [10]:
pd.read_sql("""
SELECT Product, TotalPrice
FROM sales;
""", conn)

      Product  TotalPrice
0     Monitor     2853.10
1       Phone      302.70
2      Tablet     2753.40
3       Chair      273.19
4     Printer     2504.04
...       ...         ...
1195     Desk      107.04
1196  Monitor     1325.06
1197   Tablet      873.68
1198    Chair     1050.08
1199   Tablet     2242.32

[1200 rows x 2 columns]

# Products with price greater than 500

In [11]:
pd.read_sql("""
SELECT *
FROM sales
WHERE TotalPrice > 500;
""", conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
2,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
3,ORD200006,2025-06-17,C83492,Laptop,1,664.42,986 Main St,Gift Card,Returned,TRK96417362,6,SAVE10,Facebook,664.42
4,ORD200007,2023-05-12,C41460,Monitor,5,149.55,706 Main St,Cash,Shipped,TRK78809193,9,FREESHIP,Facebook,747.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
812,ORD201194,2023-11-19,C29885,Printer,3,189.44,725 Main St,Cash,Pending,TRK62067865,4,FREESHIP,Email,568.32
813,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,no Coupon,Facebook,1325.06
814,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
815,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
816,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

# Orders paid using Credit Card

In [12]:
pd.read_sql("""
SELECT *
FROM sales
WHERE PaymentMethod='Credit Card';
""", conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
1,ORD200005,2023-10-23,C37249,Phone,2,245.86,934 Main St,Credit Card,Shipped,TRK72976927,4,SAVE10,Instagram,491.72
2,ORD200009,2023-11-21,C31946,Desk,4,509.38,102 Main St,Credit Card,Shipped,TRK33478363,6,SAVE10,Google,2037.52
3,ORD200010,2023-12-29,C43443,Tablet,5,625.97,333 Main St,Credit Card,Returned,TRK98859248,9,WINTER15,Instagram,3129.85
4,ORD200013,2023-08-30,C88348,Laptop,3,201.49,903 Main St,Credit Card,Returned,TRK81913874,4,FREESHIP,Facebook,604.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,ORD201174,2023-11-27,C50159,Printer,3,222.34,105 Main St,Credit Card,Returned,TRK53737452,5,WINTER15,Email,667.02
230,ORD201178,2024-09-08,C65107,Monitor,1,70.24,456 Main St,Credit Card,Cancelled,TRK10261578,4,FREESHIP,Google,70.24
231,ORD201179,2023-01-08,C84630,Laptop,5,518.55,907 Main St,Credit Card,Cancelled,TRK48054997,6,WINTER15,Instagram,2592.75
232,ORD201190,2025-06-08,C46886,Desk,3,616.39,754 Main St,Credit Card,Shipped,TRK82791646,6,FREESHIP,Instagram,1849.17
233,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04

# Sort by Highest Price

In [13]:
pd.read_sql("""
SELECT *
FROM sales
ORDER BY TotalPrice DESC;
""", conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200789,2023-08-17,C57276,Tablet,5,691.28,183 Main St,Online,Delivered,TRK75899752,10,SAVE10,Email,3456.40
1,ORD201122,2023-06-07,C38840,Monitor,5,678.19,766 Main St,Online,Returned,TRK32496970,8,no Coupon,Facebook,3390.95
2,ORD200632,2023-05-02,C67260,Laptop,5,678.16,463 Main St,Gift Card,Delivered,TRK38229104,7,WINTER15,Facebook,3390.80
3,ORD200469,2023-11-26,C13877,Chair,5,676.98,893 Main St,Cash,Cancelled,TRK17254691,5,no Coupon,Facebook,3384.90
4,ORD200328,2023-02-28,C18404,Tablet,5,674.04,546 Main St,Online,Cancelled,TRK89401624,7,SAVE10,Google,3370.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD200336,2023-12-29,C88174,Laptop,1,18.20,441 Main St,Debit Card,Pending,TRK10143345,4,SAVE10,Instagram,18.20
1196,ORD200542,2023-11-14,C49726,Tablet,1,17.98,934 Main St,Cash,Cancelled,TRK20739460,6,FREESHIP,Email,17.98
1197,ORD200240,2023-07-12,C14983,Tablet,1,17.24,255 Main St,Online,Pending,TRK93444157,2,FREESHIP,Instagram,17.24
1198,ORD200863,2024-05-20,C98276,Phone,1,14.06,471 Main St,Credit Card,Pending,TRK74207282,5,SAVE10,Referral,14.06
1199,ORD201161,2023-10-16,C32570,Phone,1,11.39,826 Main St,Cash,Cancelled,TRK35969968,6,WINTER15,Email,11.39

# Sort by Lowest Price

In [14]:
pd.read_sql("""
SELECT *
FROM sales
ORDER BY TotalPrice ASC;
""", conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD201161,2023-10-16,C32570,Phone,1,11.39,826 Main St,Cash,Cancelled,TRK35969968,6,WINTER15,Email,11.39
1,ORD200863,2024-05-20,C98276,Phone,1,14.06,471 Main St,Credit Card,Pending,TRK74207282,5,SAVE10,Referral,14.06
2,ORD200240,2023-07-12,C14983,Tablet,1,17.24,255 Main St,Online,Pending,TRK93444157,2,FREESHIP,Instagram,17.24
3,ORD200542,2023-11-14,C49726,Tablet,1,17.98,934 Main St,Cash,Cancelled,TRK20739460,6,FREESHIP,Email,17.98
4,ORD200336,2023-12-29,C88174,Laptop,1,18.20,441 Main St,Debit Card,Pending,TRK10143345,4,SAVE10,Instagram,18.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD200328,2023-02-28,C18404,Tablet,5,674.04,546 Main St,Online,Cancelled,TRK89401624,7,SAVE10,Google,3370.20
1196,ORD200469,2023-11-26,C13877,Chair,5,676.98,893 Main St,Cash,Cancelled,TRK17254691,5,no Coupon,Facebook,3384.90
1197,ORD200632,2023-05-02,C67260,Laptop,5,678.16,463 Main St,Gift Card,Delivered,TRK38229104,7,WINTER15,Facebook,3390.80
1198,ORD201122,2023-06-07,C38840,Monitor,5,678.19,766 Main St,Online,Returned,TRK32496970,8,no Coupon,Facebook,3390.95
1199,ORD200789,2023-08-17,C57276,Tablet,5,691.28,183 Main St,Online,Delivered,TRK75899752,10,SAVE10,Email,3456.40

# Count Total Orders

In [15]:
pd.read_sql("""
SELECT COUNT(*) AS TotalOrders
FROM sales;
""", conn)

   TotalOrders
0         1200

# Average Price

In [16]:
pd.read_sql("""
SELECT AVG(TotalPrice) AS AveragePrice
FROM sales;
""", conn)

   AveragePrice
0     1053.9683

# Maximum Price

In [17]:
pd.read_sql("""
SELECT MAX(TotalPrice) AS MaximumPrice
FROM sales;
""", conn)

   MaximumPrice
0        3456.4

# Minimum Price

In [18]:
pd.read_sql("""
SELECT MIN(TotalPrice) AS MinimumPrice
FROM sales;
""", conn)

   MinimumPrice
0         11.39

# Total Revenue

In [19]:
pd.read_sql("""
SELECT SUM(TotalPrice) AS TotalRevenue
FROM sales;
""", conn)

   TotalRevenue
0    1264761.96

# Total Sales by Product

In [20]:
pd.read_sql("""
SELECT Product,
       SUM(TotalPrice) AS TotalSales
FROM sales
GROUP BY Product
ORDER BY TotalSales DESC;
""", conn)

   Product  TotalSales
0    Chair   195620.11
1  Printer   195612.61
2   Laptop   192126.56
3   Tablet   186568.95
4  Monitor   175651.41
5     Desk   167459.93
6    Phone   151722.39

# Average Quantity by Product

In [21]:
pd.read_sql("""
SELECT Product,
       AVG(Quantity) AS AverageQuantity
FROM sales
GROUP BY Product;
""", conn)

   Product  AverageQuantity
0    Chair         3.157303
1     Desk         2.988235
2   Laptop         3.092486
3  Monitor         2.944785
4    Phone         2.634615
5  Printer         2.994475
6   Tablet         2.776536

# Number of Orders by Payment Method

In [22]:
pd.read_sql("""
SELECT PaymentMethod,
       COUNT(*) AS Orders
FROM sales
GROUP BY PaymentMethod;
""", conn)

  PaymentMethod  Orders
0          Cash     246
1   Credit Card     234
2    Debit Card     232
3     Gift Card     230
4        Online     258

# Number of Orders by Status

In [23]:
pd.read_sql("""
SELECT OrderStatus,
       COUNT(*) AS TotalOrders
FROM sales
GROUP BY OrderStatus;
""", conn)

  OrderStatus  TotalOrders
0   Cancelled          250
1   Delivered          231
2     Pending          237
3    Returned          247
4     Shipped          235

# Top 5 Best Selling Products

In [24]:
pd.read_sql("""
SELECT Product,
       SUM(TotalPrice) AS Sales
FROM sales
GROUP BY Product
ORDER BY Sales DESC
LIMIT 5;
""", conn)

   Product      Sales
0    Chair  195620.11
1  Printer  195612.61
2   Laptop  192126.56
3   Tablet  186568.95
4  Monitor  175651.41

# Orders with Coupon

In [25]:
pd.read_sql("""
SELECT *
FROM sales
WHERE CouponCode IS NOT NULL;
""", conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,no Coupon,Facebook,1325.06
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

# Referral Source Statistics

In [27]:
pd.read_sql("""
SELECT ReferralSource,
       COUNT(*) AS TotalOrders
FROM sales
GROUP BY ReferralSource;
""", conn)

  ReferralSource  TotalOrders
0          Email          250
1       Facebook          228
2         Google          241
3      Instagram          259
4       Referral          222

# Customers Who Purchased More Than One Item

In [29]:
pd.read_sql("""
SELECT CustomerID,
       SUM(Quantity) AS TotalItems
FROM sales
GROUP BY CustomerID
HAVING TotalItems > 1;
""", conn)

    CustomerID  TotalItems
0       C10002           3
1       C10054           2
2       C10126           2
3       C10154           4
4       C10211           5
..         ...         ...
935     C99271           2
936     C99683           5
937     C99775           4
938     C99879           3
939     C99904           2

[940 rows x 2 columns]

# Close Database

In [30]:
conn.close()